export type Game = {
  slug: string;
  name: string;
  shortName: string;
  color: string;
  platform: string;
  releaseYear: number;
  generation: number;
  categories: string[];
  description: string;
  stats: {
    racers: number;
    runs: number;
    categories: number;
  };
};

export const GAMES: Game[] = [
  // ---- actively raced by the crew ----
  {
    slug: "pokemon-red",
    name: "Pokémon Red",
    shortName: "RED",
    color: "#c0392b",
    platform: "Game Boy",
    generation: 1,
    releaseYear: 1996,
    categories: ["Any%", "Glitchless"],
    description: "The one that started the crew's rivalry.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-crystal",
    name: "Pokémon Crystal",
    shortName: "CRY",
    color: "#3b8fc4",
    platform: "Game Boy Color",
    generation: 2,
    releaseYear: 2000,
    categories: ["Any%", "100%"],
    description: "Johto's night-and-day gimmick, speedran to death.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-emerald",
    name: "Pokémon Emerald",
    shortName: "EMR",
    color: "#2e9e5b",
    platform: "Game Boy Advance",
    generation: 3,
    releaseYear: 2004,
    categories: ["Any%", "Glitchless"],
    description: "Hoenn's hardest category, glitchless only.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-fire-red",
    name: "Pokémon FireRed",
    shortName: "FR",
    color: "#e0703f",
    platform: "Game Boy Advance",
    generation: 3,
    releaseYear: 2004,
    categories: ["Any%", "Randomizer"],
    description: "Kanto remake — same route, faster shoes.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },

  // ---- the rest of the mainline series — nobody's raced these yet ----
  {
    slug: "pokemon-blue",
    name: "Pokémon Blue",
    shortName: "BLU",
    color: "#2f6fb0",
    platform: "Game Boy",
    generation: 1,
    releaseYear: 1996,
    categories: ["Any%", "Glitchless"],
    description: "Same Kanto, mirrored sprites, eternal debate over which starter is faster.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-green",
    name: "Pokémon Green",
    shortName: "GRN",
    color: "#3f9d5c",
    platform: "Game Boy",
    generation: 1,
    releaseYear: 1996,
    categories: ["Any%"],
    description: "The original Japan-only release, before Red and Blue went west.",
    stats: { racers: 0, runs: 0, categories: 1 },
  },
  {
    slug: "pokemon-yellow",
    name: "Pokémon Yellow",
    shortName: "YEL",
    color: "#e8c800",
    platform: "Game Boy",
    generation: 1,
    releaseYear: 1998,
    categories: ["Any%", "Glitchless"],
    description: "Pikachu follows you around. The route barely changes.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-gold",
    name: "Pokémon Gold",
    shortName: "GLD",
    color: "#c9a227",
    platform: "Game Boy Color",
    generation: 2,
    releaseYear: 1999,
    categories: ["Any%", "Glitchless"],
    description: "Two regions in one cartridge, and twice the route to learn.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-silver",
    name: "Pokémon Silver",
    shortName: "SLV",
    color: "#9aa0a6",
    platform: "Game Boy Color",
    generation: 2,
    releaseYear: 1999,
    categories: ["Any%", "Glitchless"],
    description: "Gold's twin, minus the Celebi event, plus the same grind.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-ruby",
    name: "Pokémon Ruby",
    shortName: "RUB",
    color: "#a4243b",
    platform: "Game Boy Advance",
    generation: 3,
    releaseYear: 2002,
    categories: ["Any%", "Glitchless"],
    description: "Hoenn's team-based storyline, raced without a Wallace Cup.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-sapphire",
    name: "Pokémon Sapphire",
    shortName: "SAP",
    color: "#2467a8",
    platform: "Game Boy Advance",
    generation: 3,
    releaseYear: 2002,
    categories: ["Any%", "Glitchless"],
    description: "Ruby's mirror, Team Aqua edition.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-leaf-green",
    name: "Pokémon LeafGreen",
    shortName: "LG",
    color: "#4a9c5d",
    platform: "Game Boy Advance",
    generation: 3,
    releaseYear: 2004,
    categories: ["Any%", "Randomizer"],
    description: "FireRed's twin — same Kanto remake, green box this time.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-diamond",
    name: "Pokémon Diamond",
    shortName: "DIA",
    color: "#5c7cba",
    platform: "Nintendo DS",
    generation: 4,
    releaseYear: 2006,
    categories: ["Any%", "Glitchless"],
    description: "Sinnoh's slow menus make every second count double.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-pearl",
    name: "Pokémon Pearl",
    shortName: "PRL",
    color: "#d97a9c",
    platform: "Nintendo DS",
    generation: 4,
    releaseYear: 2006,
    categories: ["Any%", "Glitchless"],
    description: "Diamond's counterpart, same Sinnoh slog.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-platinum",
    name: "Pokémon Platinum",
    shortName: "PLT",
    color: "#7d8b99",
    platform: "Nintendo DS",
    generation: 4,
    releaseYear: 2008,
    categories: ["Any%", "Glitchless"],
    description: "The Distortion World adds a whole extra dungeon to route.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-heartgold",
    name: "Pokémon HeartGold",
    shortName: "HG",
    color: "#d4a017",
    platform: "Nintendo DS",
    generation: 4,
    releaseYear: 2009,
    categories: ["Any%", "Glitchless"],
    description: "Gold remade with a Pokéwalker nobody speedruns with.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-soulsilver",
    name: "Pokémon SoulSilver",
    shortName: "SS",
    color: "#b6bcc4",
    platform: "Nintendo DS",
    generation: 4,
    releaseYear: 2009,
    categories: ["Any%", "Glitchless"],
    description: "Silver remade, Lyra's hairstyle unchanged.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-black",
    name: "Pokémon Black",
    shortName: "BLK",
    color: "#2b2b30",
    platform: "Nintendo DS",
    generation: 5,
    releaseYear: 2010,
    categories: ["Any%", "Glitchless"],
    description: "All-new Pokémon, all-new Unova, all-new route to learn from scratch.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-white",
    name: "Pokémon White",
    shortName: "WHT",
    color: "#e6e6ea",
    platform: "Nintendo DS",
    generation: 5,
    releaseYear: 2010,
    categories: ["Any%", "Glitchless"],
    description: "Black's counterpart — different version-exclusive route tweaks.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-black-2",
    name: "Pokémon Black 2",
    shortName: "B2",
    color: "#3a3a90",
    platform: "Nintendo DS",
    generation: 5,
    releaseYear: 2012,
    categories: ["Any%", "Glitchless"],
    description: "A true sequel — new gyms, new route, same region.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-white-2",
    name: "Pokémon White 2",
    shortName: "W2",
    color: "#c99a3f",
    platform: "Nintendo DS",
    generation: 5,
    releaseYear: 2012,
    categories: ["Any%", "Glitchless"],
    description: "Black 2's twin, with its own gym leader shuffle.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-x",
    name: "Pokémon X",
    shortName: "X",
    color: "#2a6fbd",
    platform: "Nintendo 3DS",
    generation: 6,
    releaseYear: 2013,
    categories: ["Any%", "Glitchless"],
    description: "The jump to 3D — Kalos routing is all about the bike.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-y",
    name: "Pokémon Y",
    shortName: "Y",
    color: "#c0334d",
    platform: "Nintendo 3DS",
    generation: 6,
    releaseYear: 2013,
    categories: ["Any%", "Glitchless"],
    description: "X's mirror, same Kalos, same bike-heavy route.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-omega-ruby",
    name: "Pokémon Omega Ruby",
    shortName: "OR",
    color: "#c62840",
    platform: "Nintendo 3DS",
    generation: 6,
    releaseYear: 2014,
    categories: ["Any%", "Glitchless"],
    description: "Hoenn remade in 3D, DexNav grinding optional for a race.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-alpha-sapphire",
    name: "Pokémon Alpha Sapphire",
    shortName: "AS",
    color: "#2874b5",
    platform: "Nintendo 3DS",
    generation: 6,
    releaseYear: 2014,
    categories: ["Any%", "Glitchless"],
    description: "Omega Ruby's counterpart, same remade Hoenn.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-sun",
    name: "Pokémon Sun",
    shortName: "SUN",
    color: "#e08a2e",
    platform: "Nintendo 3DS",
    generation: 7,
    releaseYear: 2016,
    categories: ["Any%", "Glitchless"],
    description: "Trials instead of gyms — Alola resets the whole route metagame.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-moon",
    name: "Pokémon Moon",
    shortName: "MOON",
    color: "#5b4b9e",
    platform: "Nintendo 3DS",
    generation: 7,
    releaseYear: 2016,
    categories: ["Any%", "Glitchless"],
    description: "Sun's nighttime counterpart, same island trials.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-ultra-sun",
    name: "Pokémon Ultra Sun",
    shortName: "USUN",
    color: "#d9622b",
    platform: "Nintendo 3DS",
    generation: 7,
    releaseYear: 2017,
    categories: ["Any%", "Glitchless"],
    description: "Alola again, with Ultra Wormholes and extra cutscenes to skip.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-ultra-moon",
    name: "Pokémon Ultra Moon",
    shortName: "UMOON",
    color: "#4b3a8f",
    platform: "Nintendo 3DS",
    generation: 7,
    releaseYear: 2017,
    categories: ["Any%", "Glitchless"],
    description: "Ultra Sun's counterpart, same expanded Alola.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-lets-go-pikachu",
    name: "Pokémon Let's Go, Pikachu!",
    shortName: "LGP",
    color: "#e8c800",
    platform: "Nintendo Switch",
    generation: 7,
    releaseYear: 2018,
    categories: ["Any%"],
    description: "Kanto again, catch-'em-all controls, no random encounters to route around.",
    stats: { racers: 0, runs: 0, categories: 1 },
  },
  {
    slug: "pokemon-lets-go-eevee",
    name: "Pokémon Let's Go, Eevee!",
    shortName: "LGE",
    color: "#a9754f",
    platform: "Nintendo Switch",
    generation: 7,
    releaseYear: 2018,
    categories: ["Any%"],
    description: "Let's Go Pikachu's counterpart, Eevee riding shotgun instead.",
    stats: { racers: 0, runs: 0, categories: 1 },
  },
  {
    slug: "pokemon-sword",
    name: "Pokémon Sword",
    shortName: "SWD",
    color: "#00a3ad",
    platform: "Nintendo Switch",
    generation: 8,
    releaseYear: 2019,
    categories: ["Any%", "Glitchless"],
    description: "Galar's stadiums and Dynamax fights, routed for speed.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-shield",
    name: "Pokémon Shield",
    shortName: "SHD",
    color: "#a13a8f",
    platform: "Nintendo Switch",
    generation: 8,
    releaseYear: 2019,
    categories: ["Any%", "Glitchless"],
    description: "Sword's counterpart, same Galar, different exclusives.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-brilliant-diamond",
    name: "Pokémon Brilliant Diamond",
    shortName: "BD",
    color: "#6f93c9",
    platform: "Nintendo Switch",
    generation: 8,
    releaseYear: 2021,
    categories: ["Any%", "Glitchless"],
    description: "Diamond remade chibi-style, Underground digging skipped entirely.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-shining-pearl",
    name: "Pokémon Shining Pearl",
    shortName: "SP",
    color: "#e08fae",
    platform: "Nintendo Switch",
    generation: 8,
    releaseYear: 2021,
    categories: ["Any%", "Glitchless"],
    description: "Brilliant Diamond's counterpart, same remade Sinnoh.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-legends-arceus",
    name: "Pokémon Legends: Arceus",
    shortName: "PLA",
    color: "#c9b28a",
    platform: "Nintendo Switch",
    generation: 8,
    releaseYear: 2022,
    categories: ["Any%"],
    description: "Open-zone Hisui with no trainer battles slowing the route down.",
    stats: { racers: 0, runs: 0, categories: 1 },
  },
  {
    slug: "pokemon-scarlet",
    name: "Pokémon Scarlet",
    shortName: "SCR",
    color: "#c0392b",
    platform: "Nintendo Switch",
    generation: 9,
    releaseYear: 2022,
    categories: ["Any%", "Glitchless"],
    description: "Fully open-world Paldea — three storylines, one race clock.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-violet",
    name: "Pokémon Violet",
    shortName: "VIO",
    color: "#6a4c9c",
    platform: "Nintendo Switch",
    generation: 9,
    releaseYear: 2022,
    categories: ["Any%", "Glitchless"],
    description: "Scarlet's counterpart, same open Paldea.",
    stats: { racers: 0, runs: 0, categories: 2 },
  },
  {
    slug: "pokemon-legends-za",
    name: "Pokémon Legends: Z-A",
    shortName: "Z-A",
    color: "#1c1c2e",
    platform: "Nintendo Switch",
    generation: 9,
    releaseYear: 2025,
    categories: ["Any%"],
    description: "Lumiose City reimagined — Mega Evolution takes center stage in real time.",
    stats: { racers: 0, runs: 0, categories: 1 },
  },
];

export function getGameBySlug(slug: string): Game | undefined {
  return GAMES.find((game) => game.slug === slug);
}
