/**
 * Maps each game slug to the PokeAPI species name of its box-art mascot.
 * Used to pull real Pokémon artwork onto the game cards.
 */
export const GAME_MASCOTS: Record<string, string> = {
  "pokemon-red": "charizard",
  "pokemon-blue": "blastoise",
  "pokemon-green": "blastoise",
  "pokemon-yellow": "pikachu",
  "pokemon-gold": "ho-oh",
  "pokemon-silver": "lugia",
  "pokemon-crystal": "suicune",
  "pokemon-ruby": "groudon",
  "pokemon-sapphire": "kyogre",
  "pokemon-emerald": "rayquaza",
  "pokemon-fire-red": "charizard",
  "pokemon-leaf-green": "venusaur",
  "pokemon-diamond": "dialga",
  "pokemon-pearl": "palkia",
  "pokemon-platinum": "giratina-altered",
  "pokemon-heartgold": "ho-oh",
  "pokemon-soulsilver": "lugia",
  "pokemon-black": "reshiram",
  "pokemon-white": "zekrom",
  "pokemon-black-2": "kyurem-black",
  "pokemon-white-2": "kyurem-white",
  "pokemon-x": "xerneas",
  "pokemon-y": "yveltal",
  "pokemon-omega-ruby": "groudon-primal",
  "pokemon-alpha-sapphire": "kyogre-primal",
  "pokemon-sun": "solgaleo",
  "pokemon-moon": "lunala",
  "pokemon-ultra-sun": "necrozma-dusk",
  "pokemon-ultra-moon": "necrozma-dawn",
  "pokemon-lets-go-pikachu": "pikachu",
  "pokemon-lets-go-eevee": "eevee",
  "pokemon-sword": "zacian",
  "pokemon-shield": "zamazenta",
  "pokemon-brilliant-diamond": "dialga",
  "pokemon-shining-pearl": "palkia",
  "pokemon-legends-arceus": "arceus",
  "pokemon-scarlet": "koraidon",
  "pokemon-violet": "miraidon",
};
