-- The initial seed (see the `insert into public.games` block near the top
-- of schema.sql) only covered 4 of the ~38 games listed in
-- src/lib/games.ts. Any other game had no row here, so `games.id` was null
-- for it — which meant registering a run for it silently skipped the
-- `runs` insert in SetActiveGameButton (see gameId check there), making
-- the "Runs" stat on that game's page stay stuck at 0 forever. This backfills
-- the rest of the catalog so every game can log runs. Safe to re-run,
-- standalone from schema.sql — generated from src/lib/games.ts to keep the
-- data in sync (no manual transcription).

insert into public.games (slug, name, short_name, color, platform, description)
values
  ('pokemon-red', 'Pokémon Red', 'RED', '#c0392b', 'Game Boy', 'The one that started the crew''s rivalry.'),
  ('pokemon-crystal', 'Pokémon Crystal', 'CRY', '#3b8fc4', 'Game Boy Color', 'Johto''s night-and-day gimmick, speedran to death.'),
  ('pokemon-emerald', 'Pokémon Emerald', 'EMR', '#2e9e5b', 'Game Boy Advance', 'Hoenn''s hardest category, glitchless only.'),
  ('pokemon-fire-red', 'Pokémon FireRed', 'FR', '#e0703f', 'Game Boy Advance', 'Kanto remake — same route, faster shoes.'),
  ('pokemon-blue', 'Pokémon Blue', 'BLU', '#2f6fb0', 'Game Boy', 'Same Kanto, mirrored sprites, eternal debate over which starter is faster.'),
  ('pokemon-green', 'Pokémon Green', 'GRN', '#3f9d5c', 'Game Boy', 'The original Japan-only release, before Red and Blue went west.'),
  ('pokemon-yellow', 'Pokémon Yellow', 'YEL', '#e8c800', 'Game Boy', 'Pikachu follows you around. The route barely changes.'),
  ('pokemon-gold', 'Pokémon Gold', 'GLD', '#c9a227', 'Game Boy Color', 'Two regions in one cartridge, and twice the route to learn.'),
  ('pokemon-silver', 'Pokémon Silver', 'SLV', '#9aa0a6', 'Game Boy Color', 'Gold''s twin, minus the Celebi event, plus the same grind.'),
  ('pokemon-ruby', 'Pokémon Ruby', 'RUB', '#a4243b', 'Game Boy Advance', 'Hoenn''s team-based storyline, raced without a Wallace Cup.'),
  ('pokemon-sapphire', 'Pokémon Sapphire', 'SAP', '#2467a8', 'Game Boy Advance', 'Ruby''s mirror, Team Aqua edition.'),
  ('pokemon-leaf-green', 'Pokémon LeafGreen', 'LG', '#4a9c5d', 'Game Boy Advance', 'FireRed''s twin — same Kanto remake, green box this time.'),
  ('pokemon-diamond', 'Pokémon Diamond', 'DIA', '#5c7cba', 'Nintendo DS', 'Sinnoh''s slow menus make every second count double.'),
  ('pokemon-pearl', 'Pokémon Pearl', 'PRL', '#d97a9c', 'Nintendo DS', 'Diamond''s counterpart, same Sinnoh slog.'),
  ('pokemon-platinum', 'Pokémon Platinum', 'PLT', '#7d8b99', 'Nintendo DS', 'The Distortion World adds a whole extra dungeon to route.'),
  ('pokemon-heartgold', 'Pokémon HeartGold', 'HG', '#d4a017', 'Nintendo DS', 'Gold remade with a Pokéwalker nobody speedruns with.'),
  ('pokemon-soulsilver', 'Pokémon SoulSilver', 'SS', '#b6bcc4', 'Nintendo DS', 'Silver remade, Lyra''s hairstyle unchanged.'),
  ('pokemon-black', 'Pokémon Black', 'BLK', '#2b2b30', 'Nintendo DS', 'All-new Pokémon, all-new Unova, all-new route to learn from scratch.'),
  ('pokemon-white', 'Pokémon White', 'WHT', '#e6e6ea', 'Nintendo DS', 'Black''s counterpart — different version-exclusive route tweaks.'),
  ('pokemon-black-2', 'Pokémon Black 2', 'B2', '#3a3a90', 'Nintendo DS', 'A true sequel — new gyms, new route, same region.'),
  ('pokemon-white-2', 'Pokémon White 2', 'W2', '#c99a3f', 'Nintendo DS', 'Black 2''s twin, with its own gym leader shuffle.'),
  ('pokemon-x', 'Pokémon X', 'X', '#2a6fbd', 'Nintendo 3DS', 'The jump to 3D — Kalos routing is all about the bike.'),
  ('pokemon-y', 'Pokémon Y', 'Y', '#c0334d', 'Nintendo 3DS', 'X''s mirror, same Kalos, same bike-heavy route.'),
  ('pokemon-omega-ruby', 'Pokémon Omega Ruby', 'OR', '#c62840', 'Nintendo 3DS', 'Hoenn remade in 3D, DexNav grinding optional for a race.'),
  ('pokemon-alpha-sapphire', 'Pokémon Alpha Sapphire', 'AS', '#2874b5', 'Nintendo 3DS', 'Omega Ruby''s counterpart, same remade Hoenn.'),
  ('pokemon-sun', 'Pokémon Sun', 'SUN', '#e08a2e', 'Nintendo 3DS', 'Trials instead of gyms — Alola resets the whole route metagame.'),
  ('pokemon-moon', 'Pokémon Moon', 'MOON', '#5b4b9e', 'Nintendo 3DS', 'Sun''s nighttime counterpart, same island trials.'),
  ('pokemon-ultra-sun', 'Pokémon Ultra Sun', 'USUN', '#d9622b', 'Nintendo 3DS', 'Alola again, with Ultra Wormholes and extra cutscenes to skip.'),
  ('pokemon-ultra-moon', 'Pokémon Ultra Moon', 'UMOON', '#4b3a8f', 'Nintendo 3DS', 'Ultra Sun''s counterpart, same expanded Alola.'),
  ('pokemon-lets-go-pikachu', 'Pokémon Let''s Go, Pikachu!', 'LGP', '#e8c800', 'Nintendo Switch', 'Kanto again, catch-''em-all controls, no random encounters to route around.'),
  ('pokemon-lets-go-eevee', 'Pokémon Let''s Go, Eevee!', 'LGE', '#a9754f', 'Nintendo Switch', 'Let''s Go Pikachu''s counterpart, Eevee riding shotgun instead.'),
  ('pokemon-sword', 'Pokémon Sword', 'SWD', '#00a3ad', 'Nintendo Switch', 'Galar''s stadiums and Dynamax fights, routed for speed.'),
  ('pokemon-shield', 'Pokémon Shield', 'SHD', '#a13a8f', 'Nintendo Switch', 'Sword''s counterpart, same Galar, different exclusives.'),
  ('pokemon-brilliant-diamond', 'Pokémon Brilliant Diamond', 'BD', '#6f93c9', 'Nintendo Switch', 'Diamond remade chibi-style, Underground digging skipped entirely.'),
  ('pokemon-shining-pearl', 'Pokémon Shining Pearl', 'SP', '#e08fae', 'Nintendo Switch', 'Brilliant Diamond''s counterpart, same remade Sinnoh.'),
  ('pokemon-legends-arceus', 'Pokémon Legends: Arceus', 'PLA', '#c9b28a', 'Nintendo Switch', 'Open-zone Hisui with no trainer battles slowing the route down.'),
  ('pokemon-scarlet', 'Pokémon Scarlet', 'SCR', '#c0392b', 'Nintendo Switch', 'Fully open-world Paldea — three storylines, one race clock.'),
  ('pokemon-violet', 'Pokémon Violet', 'VIO', '#6a4c9c', 'Nintendo Switch', 'Scarlet''s counterpart, same open Paldea.')
on conflict (slug) do nothing;

insert into public.categories (game_id, name)
select g.id, c.name
from (values
  ('pokemon-red', 'Any%'),
  ('pokemon-red', 'Glitchless'),
  ('pokemon-crystal', 'Any%'),
  ('pokemon-crystal', '100%'),
  ('pokemon-emerald', 'Any%'),
  ('pokemon-emerald', 'Glitchless'),
  ('pokemon-fire-red', 'Any%'),
  ('pokemon-fire-red', 'Randomizer'),
  ('pokemon-blue', 'Any%'),
  ('pokemon-blue', 'Glitchless'),
  ('pokemon-green', 'Any%'),
  ('pokemon-yellow', 'Any%'),
  ('pokemon-yellow', 'Glitchless'),
  ('pokemon-gold', 'Any%'),
  ('pokemon-gold', 'Glitchless'),
  ('pokemon-silver', 'Any%'),
  ('pokemon-silver', 'Glitchless'),
  ('pokemon-ruby', 'Any%'),
  ('pokemon-ruby', 'Glitchless'),
  ('pokemon-sapphire', 'Any%'),
  ('pokemon-sapphire', 'Glitchless'),
  ('pokemon-leaf-green', 'Any%'),
  ('pokemon-leaf-green', 'Randomizer'),
  ('pokemon-diamond', 'Any%'),
  ('pokemon-diamond', 'Glitchless'),
  ('pokemon-pearl', 'Any%'),
  ('pokemon-pearl', 'Glitchless'),
  ('pokemon-platinum', 'Any%'),
  ('pokemon-platinum', 'Glitchless'),
  ('pokemon-heartgold', 'Any%'),
  ('pokemon-heartgold', 'Glitchless'),
  ('pokemon-soulsilver', 'Any%'),
  ('pokemon-soulsilver', 'Glitchless'),
  ('pokemon-black', 'Any%'),
  ('pokemon-black', 'Glitchless'),
  ('pokemon-white', 'Any%'),
  ('pokemon-white', 'Glitchless'),
  ('pokemon-black-2', 'Any%'),
  ('pokemon-black-2', 'Glitchless'),
  ('pokemon-white-2', 'Any%'),
  ('pokemon-white-2', 'Glitchless'),
  ('pokemon-x', 'Any%'),
  ('pokemon-x', 'Glitchless'),
  ('pokemon-y', 'Any%'),
  ('pokemon-y', 'Glitchless'),
  ('pokemon-omega-ruby', 'Any%'),
  ('pokemon-omega-ruby', 'Glitchless'),
  ('pokemon-alpha-sapphire', 'Any%'),
  ('pokemon-alpha-sapphire', 'Glitchless'),
  ('pokemon-sun', 'Any%'),
  ('pokemon-sun', 'Glitchless'),
  ('pokemon-moon', 'Any%'),
  ('pokemon-moon', 'Glitchless'),
  ('pokemon-ultra-sun', 'Any%'),
  ('pokemon-ultra-sun', 'Glitchless'),
  ('pokemon-ultra-moon', 'Any%'),
  ('pokemon-ultra-moon', 'Glitchless'),
  ('pokemon-lets-go-pikachu', 'Any%'),
  ('pokemon-lets-go-eevee', 'Any%'),
  ('pokemon-sword', 'Any%'),
  ('pokemon-sword', 'Glitchless'),
  ('pokemon-shield', 'Any%'),
  ('pokemon-shield', 'Glitchless'),
  ('pokemon-brilliant-diamond', 'Any%'),
  ('pokemon-brilliant-diamond', 'Glitchless'),
  ('pokemon-shining-pearl', 'Any%'),
  ('pokemon-shining-pearl', 'Glitchless'),
  ('pokemon-legends-arceus', 'Any%'),
  ('pokemon-scarlet', 'Any%'),
  ('pokemon-scarlet', 'Glitchless'),
  ('pokemon-violet', 'Any%'),
  ('pokemon-violet', 'Glitchless')
) as c(slug, name)
join public.games g on g.slug = c.slug
on conflict (game_id, name) do nothing;
